#!/bin/bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/pi/n/bin"

node formatter/formatter.js

git add --all
git commit -m "$(date --iso-8601)"
git push -u origin master

rm -rf leastportals/cache/
rm -rf seum/cache/
