[book]
authors = ["NeKz"]
language = "en"
multilingual = false
src = "src"
title = ".dem"

[output.html]
git-repository-url = "https://github.com/NeKzor/nekzor.github.io"
git-repository-icon = "fa-github"
